//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignaturePad.DomainModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspHoSoCanBo
    {
        public long IdCanBo { get; set; }
        public string ho_ten { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string gioi_tinh { get; set; }
        public string so_dien_thoai { get; set; }
        public string url_avatar { get; set; }
        public string name_avatar { get; set; }
        public string email { get; set; }
        public string chuc_vu { get; set; }
        public string cb_trang_thai_lam_viec { get; set; }
        public string so_hieu_giay_to { get; set; }
        public Nullable<System.DateTime> ngay_bat_dau_cong_tac { get; set; }
        public string cap_bac_luong { get; set; }
        public Nullable<long> ma_bin_ngan_hang { get; set; }
        public string cb_ngan_hang { get; set; }
        public string ho_ten_chu_tai_khoan { get; set; }
        public string so_tai_khoan { get; set; }
        public string cb_tinh { get; set; }
        public string cb_quan_huyen { get; set; }
        public string cb_xa_phuong { get; set; }
        public string dia_chi { get; set; }
        public Nullable<long> IdUser { get; set; }
    }
}
