//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignaturePad.DomainModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspStoreDocument
    {
        public long IdDocument { get; set; }
        public string ten_file { get; set; }
        public string url_file { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public string duoi_file { get; set; }
        public Nullable<long> IdUser { get; set; }
        public Nullable<int> kich_thuoc { get; set; }
        public Nullable<bool> is_xoa { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<long> IdFoder { get; set; }
        public Nullable<long> IdHienVat { get; set; }
    
        public virtual AspDetailUser AspDetailUser { get; set; }
        public virtual AspFolder AspFolder { get; set; }
    }
}
